# Generated by Django 5.2.14 on 2026-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0029_rename_accounting__client__b1c2a3_idx_accounting__client__3810b4_idx_and_more"),
        ("mydata", "0003_remove_vatrecord_unique_client_mark_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vatrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vatrecord",
            name="expense_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("361", "Εμπορεύματα & Α' Ύλες"),
                    ("362", "Πάγια"),
                    ("363", "Λοιπές Δαπάνες"),
                    ("364", "Ενδοκοιν. Εμπορεύματα"),
                    ("365", "Ενδοκοιν. Πάγια"),
                    ("366", "Ενδοκοιν. Λοιπές Δαπάνες"),
                ],
                db_index=True,
                default="",
                help_text="Κωδικός εισροών ΑΑΔΕ (361-364)",
                max_length=3,
                verbose_name="Κατηγορία Δαπάνης",
            ),
        ),
        migrations.AlterField(
            model_name="vatrecord",
            name="inv_type",
            field=models.CharField(
                db_index=True, help_text="π.χ. 1.1, 2.1, 5.1, ΕΙΣΡΟΕΣ_362", max_length=20, verbose_name="Τύπος Παραστατικού"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vatrecord",
            unique_together={("client", "mark", "expense_category")},
        ),
    ]
