# Generated by Django 5.2.14 on 2026-05-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10007_merge_20260524_1425"),
        ("mydata", "0004_alter_vatrecord_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vatrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vatrecord",
            name="income_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("301", "Εκροές 13%"),
                    ("302", "Εκροές 6%"),
                    ("303", "Εκροές 24%"),
                    ("304", "Εκροές 9%"),
                    ("305", "Εκροές 17%"),
                    ("306", "Εκροές 4%"),
                    ("309", "Εκροές μειωμένος"),
                    ("310", "Απαλλασσόμενες εκροές"),
                    ("311", "Μη υποκ. εκροές"),
                    ("342", "Ενδοκοιν. Παραδόσεις"),
                    ("345", "Ενδοκοιν. Υπηρεσίες"),
                    ("348", "Ενδοκοιν. Τρίγωνες"),
                ],
                db_index=True,
                default="",
                help_text="Κωδικός εκροών ΑΑΔΕ Φ2 (301-348)",
                max_length=3,
                verbose_name="Κωδικός Εκροών",
            ),
        ),
        migrations.AlterField(
            model_name="vatrecord",
            name="expense_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("361", "Εμπορεύματα & Α' Ύλες"),
                    ("362", "Πάγια"),
                    ("363", "Λοιπές Δαπάνες"),
                    ("364", "Ενδοκοιν. Εμπορεύματα"),
                    ("365", "Ενδοκοιν. Πάγια"),
                    ("366", "Ενδοκοιν. Λοιπές Δαπάνες"),
                ],
                db_index=True,
                default="",
                help_text="Κωδικός εισροών ΑΑΔΕ (361-366)",
                max_length=3,
                verbose_name="Κατηγορία Δαπάνης",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vatrecord",
            unique_together={("client", "mark", "expense_category", "income_code")},
        ),
    ]
