# Generated by Django 5.0.14 on 2026-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '10008_clientprofile_user'),
        ('mydata', '0006_clear_old_vatrecords'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vatrecord',
            index=models.Index(fields=['client', 'is_cancelled', 'issue_date'], name='vatrecord_client_active_idx'),
        ),
    ]
