# Generated by Django 5.0.14 on 2026-07-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "9999_add_audit_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="common_audi_timesta_c5afa9_idx",
            old_name="common_audi_timesta_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="common_audi_model_n_1f8308_idx",
            old_name="common_audi_model_n_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="common_audi_severit_5ea651_idx",
            old_name="common_audi_severit_idx",
        ),
    ]
