# Generated by Django 5.0.14 on 2026-07-29 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_filingsystemsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_reminders", models.BooleanField(default=True, verbose_name="Email υπενθυμίσεις προθεσμιών")),
                ("email_overdue", models.BooleanField(default=True, verbose_name="Email για εκπρόθεσμες υποχρεώσεις")),
                ("new_files", models.BooleanField(default=False, verbose_name="Ειδοποίηση για νέα αρχεία")),
                ("missed_calls", models.BooleanField(default=True, verbose_name="Ειδοποίηση για αναπάντητες κλήσεις")),
                ("weekly_summary", models.BooleanField(default=False, verbose_name="Εβδομαδιαία σύνοψη")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ενημερώθηκε")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Χρήστης",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ρυθμίσεις Ειδοποιήσεων Χρήστη",
                "verbose_name_plural": "Ρυθμίσεις Ειδοποιήσεων Χρηστών",
            },
        ),
    ]
