# Generated by Django 5.0.14 on 2026-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10000_merge_20251205_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="correlated_mark",
            field=models.BigIntegerField(
                blank=True, help_text="Υποχρεωτικό για πιστωτικά τύπου 5.1", null=True, verbose_name="MARK Συσχετιζόμενου"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="mydata_cancellation_mark",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="MARK Ακύρωσης"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="mydata_cancelled",
            field=models.BooleanField(default=False, verbose_name="Ακυρωμένο στο myDATA"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="mydata_cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ημ/νία Ακύρωσης myDATA"),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="vat_exemption_category",
            field=models.IntegerField(
                blank=True,
                help_text="Υποχρεωτικό όταν η κατηγορία ΦΠΑ είναι 7 (Χωρίς ΦΠΑ) — κωδικοί ΑΑΔΕ 1-31",
                null=True,
                verbose_name="Κατηγορία Εξαίρεσης ΦΠΑ",
            ),
        ),
    ]
