# Generated by Django 5.2.14 on 2026-05-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0028_unified_document_system"),
        ("accounting", "10006_door_access_log"),
    ]

    operations = []
