# Generated by Django 5.2.14 on 2026-05-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0029_rename_accounting__client__b1c2a3_idx_accounting__client__3810b4_idx_and_more"),
        ("accounting", "10006_door_access_log"),
    ]

    operations = []
