# Generated by Django 5.0.14 on 2026-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10008_rename_accounting__client__b1c2a3_idx_accounting__client__3810b4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdocument",
            name="afm_mismatch",
            field=models.BooleanField(
                default=False,
                help_text="Το έγγραφο περιέχει ΑΦΜ που δεν ταιριάζει με τον πελάτη",
                verbose_name="Αναντιστοιχία ΑΦΜ",
            ),
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Κείμενο από το PDF για αναζήτηση περιεχομένου",
                verbose_name="Εξαγόμενο Κείμενο",
            ),
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="ocr_processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ημ/νία Εξαγωγής"),
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Εκκρεμεί"),
                    ("done", "Ολοκληρώθηκε"),
                    ("failed", "Απέτυχε"),
                    ("skipped", "Παραλείφθηκε"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="Κατάσταση Εξαγωγής",
            ),
        ),
    ]
