# Generated by Django 5.0.14 on 2026-07-28 20:24

import accounting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10007_merge_20260728_2116"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clientdocument",
            new_name="accounting__client__3810b4_idx",
            old_name="accounting__client__b1c2a3_idx",
        ),
        migrations.RenameIndex(
            model_name="clientdocument",
            new_name="accounting__client__90fd79_idx",
            old_name="accounting__client__d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="clientdocument",
            new_name="accounting__obligat_a26ada_idx",
            old_name="accounting__obligat__g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedlink",
            new_name="accounting__token_ea1b45_idx",
            old_name="accounting__token_4ab5c3_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedlink",
            new_name="accounting__is_acti_321296_idx",
            old_name="accounting__is_acti_a2b3c4_idx",
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="accounting.clientprofile",
                verbose_name="Πελάτης",
            ),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="description",
            field=models.TextField(blank=True, verbose_name="Περιγραφή"),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="document_category",
            field=models.CharField(
                choices=[
                    ("registration", "Ιδρυτικά Έγγραφα"),
                    ("contracts", "Συμβάσεις"),
                    ("licenses", "Άδειες & Πιστοποιητικά"),
                    ("correspondence", "Αλληλογραφία"),
                    ("vat", "ΦΠΑ"),
                    ("apd", "ΑΠΔ/ΕΦΚΑ"),
                    ("myf", "ΜΥΦ"),
                    ("payroll", "Μισθοδοσία"),
                    ("invoices_issued", "Εκδοθέντα Τιμολόγια"),
                    ("invoices_received", "Ληφθέντα Τιμολόγια"),
                    ("bank", "Τραπεζικά"),
                    ("receipts", "Αποδείξεις"),
                    ("e1", "Ε1 - Φόρος Εισοδήματος"),
                    ("e2", "Ε2 - Ακίνητα"),
                    ("e3", "Ε3 - Οικονομικά Στοιχεία"),
                    ("enfia", "ΕΝΦΙΑ"),
                    ("balance", "Ισολογισμός"),
                    ("audit", "Έλεγχοι"),
                    ("invoices", "Τιμολόγια"),
                    ("tax", "Φορολογικά"),
                    ("efka", "ΕΦΚΑ"),
                    ("general", "Γενικά"),
                ],
                db_index=True,
                default="general",
                max_length=20,
                verbose_name="Κατηγορία",
            ),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="file",
            field=models.FileField(upload_to=accounting.models.client_document_path, verbose_name="Αρχείο"),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="file_type",
            field=models.CharField(max_length=50, verbose_name="Τύπος"),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="filename",
            field=models.CharField(max_length=255, verbose_name="Όνομα Αρχείου"),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ημ/νία Upload"),
        ),
        migrations.AlterField(
            model_name="monthlyobligation",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Χρησιμοποιήστε ClientDocument αντί αυτού",
                null=True,
                upload_to=accounting.models.obligation_upload_path,
                verbose_name="[DEPRECATED] Συνημμένο Αρχείο",
            ),
        ),
        migrations.AlterField(
            model_name="sharedlink",
            name="token",
            field=models.CharField(
                default=accounting.models.generate_share_token, max_length=64, unique=True, verbose_name="Token"
            ),
        ),
    ]
