# Generated by Django 5.0.14 on 2026-06-01 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '10007_merge_20260524_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Ο χρήστης που μπορεί να συνδεθεί στο portal για αυτόν τον πελάτη', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Λογαριασμός Πελάτη (Portal)'),
        ),
    ]
