# Generated by Django 5.0.14 on 2026-06-07 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '10008_clientprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('aade', 'ΑΑΔΕ'), ('efka', 'ΕΦΚΑ/ΚΕΑΟ'), ('other', 'Άλλο')], db_index=True, max_length=10, verbose_name='Φορέας')),
                ('description', models.CharField(max_length=200, verbose_name='Περιγραφή')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ποσό')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Προθεσμία')),
                ('payment_code', models.CharField(blank=True, max_length=50, verbose_name='Ταυτότητα Οφειλής / RF')),
                ('status', models.CharField(choices=[('outstanding', 'Ανεξόφλητη'), ('arranged', 'Σε ρύθμιση'), ('overdue', 'Ληξιπρόθεσμη'), ('paid', 'Εξοφλημένη')], db_index=True, default='outstanding', max_length=12, verbose_name='Κατάσταση')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='accounting.clientprofile', verbose_name='Πελάτης')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_liabilities', to=settings.AUTH_USER_MODEL, verbose_name='Καταχωρήθηκε από')),
            ],
            options={
                'verbose_name': 'Οφειλή Πελάτη',
                'verbose_name_plural': 'Οφειλές Πελατών',
                'ordering': ['-due_date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'source'], name='accounting__client__c42d8d_idx'), models.Index(fields=['client', 'status'], name='accounting__client__18d527_idx')],
            },
        ),
    ]
