# Generated by Django 5.2.16 on 2026-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10013_documentrequest_documentrequestitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "⏳ Εκκρεμεί"),
                    ("sending", "📤 Αποστέλλεται"),
                    ("sent", "✅ Στάλθηκε"),
                    ("failed", "❌ Απέτυχε"),
                    ("cancelled", "🚫 Ακυρώθηκε"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Κατάσταση",
            ),
        ),
    ]
