# Generated by Django 5.2.14 on 2026-05-24 10:17

from django.db import migrations, models


CHARFIELDS = [
    "afm_foreas", "afm_sizigou", "am_ika", "am_klidi", "amka",
    "arithmos_dypa", "arithmos_epixeirisis", "arithmos_gemi",
    "arithmos_katoikias", "arithmos_taftotitas", "diefthinsi_epixeirisis",
    "diefthinsi_katoikias", "dimos_epixeirisis", "dimos_katoikias", "doy",
    "eidos_taftotitas", "filo", "iban", "katigoria_vivlion", "kinito_tilefono",
    "kodikos_gemi", "kodikos_ika_ergodoti", "kodikos_taxisnet", "nomiki_morfi",
    "nomos_epixeirisis", "nomos_katoikias", "onoma", "onoma_patros",
    "onoma_xristi_gemi", "onoma_xristi_ika_ergodoti", "onoma_xristi_taxisnet",
    "poli_epixeirisis", "poli_katoikias", "prosopikos_arithmos",
    "tilefono_epixeirisis_1", "tilefono_epixeirisis_2", "tilefono_oikias_1",
    "tilefono_oikias_2", "tk_epixeirisis", "tk_katoikias", "trapeza",
]


def null_to_empty_string(apps, schema_editor):
    """Μετατροπή NULL → '' πριν αφαιρεθεί το null=True (για PostgreSQL)."""
    ClientProfile = apps.get_model("accounting", "ClientProfile")
    for field in CHARFIELDS:
        ClientProfile.objects.filter(**{field: None}).update(**{field: ""})


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10009_fix_data_integrity"),
    ]

    operations = [
        migrations.RunPython(null_to_empty_string, migrations.RunPython.noop),

        migrations.AlterField(
            model_name="clientprofile",
            name="afm_foreas",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Α.Φ.Μ. Φορέας"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="afm_sizigou",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Α.Φ.Μ Συζύγου"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="am_ika",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Α.Μ. Ι.Κ.Α."),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="am_klidi",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="ΑΜ ΚΛΕΙΔΙ"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="amka",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Α.Μ.Κ.Α."),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="arithmos_dypa",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Αριθμός Δ.ΥΠ.Α"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="arithmos_epixeirisis",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Αριθμός Επιχείρησης"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="arithmos_gemi",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Αριθμός Γ.Ε.ΜΗ."),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="arithmos_katoikias",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Αριθμός"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="arithmos_taftotitas",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Αριθμός Ταυτότητας"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="diefthinsi_epixeirisis",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Διεύθυνση Επιχείρησης"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="diefthinsi_katoikias",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Διεύθυνση Κατοικίας"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="dimos_epixeirisis",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Δήμος Επιχείρησης"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="dimos_katoikias",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Δήμος Κατοικίας"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="doy",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Δ.Ο.Υ."),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="eidos_taftotitas",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Είδος Ταυτότητας"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="filo",
            field=models.CharField(
                blank=True, choices=[("M", "Άνδρας"), ("F", "Γυναίκα")], default="", max_length=10, verbose_name="Φύλο"
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="iban",
            field=models.CharField(blank=True, default="", max_length=34, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="katigoria_vivlion",
            field=models.CharField(
                blank=True,
                choices=[("A", "Α Κατηγορία"), ("B", "Β Κατηγορία"), ("C", "Γ Κατηγορία"), ("none", "Χωρίς Βιβλία")],
                default="",
                max_length=10,
                verbose_name="Κατηγορία Βιβλίων",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="kinito_tilefono",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Κινητό τηλέφωνο"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="kodikos_gemi",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Κωδικός Γ.Ε.ΜΗ."),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="kodikos_ika_ergodoti",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Κωδικός Ι.Κ.Α. Εργοδότη"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="kodikos_taxisnet",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Κωδικός Taxis Net"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="nomiki_morfi",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Νομική Μορφή"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="nomos_epixeirisis",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Νομός Επιχείρησης"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="nomos_katoikias",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Νομός Κατοικίας"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="onoma",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Όνομα"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="onoma_patros",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Όνομα Πατρός"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="onoma_xristi_gemi",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Όνομα Χρήστη Γ.Ε.ΜΗ."),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="onoma_xristi_ika_ergodoti",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Όνομα Χρήστη Ι.Κ.Α. Εργοδότη"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="onoma_xristi_taxisnet",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Όνομα Χρήστη Taxis Net"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="poli_epixeirisis",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Πόλη Επιχείρησης"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="poli_katoikias",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Πόλη Κατοικίας"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="prosopikos_arithmos",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Προσωπικός Αριθμός"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="tilefono_epixeirisis_1",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Τηλέφωνο Επιχείρησης 1"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="tilefono_epixeirisis_2",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Τηλέφωνο Επιχείρησης 2"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="tilefono_oikias_1",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Τηλέφωνο Οικίας 1"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="tilefono_oikias_2",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Τηλέφωνο Οικίας 2"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="tk_epixeirisis",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Τ.Κ. Επιχείρησης"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="tk_katoikias",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="T.K. Κατοικίας"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="trapeza",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Τράπεζα"),
        ),
    ]
