# Generated by Django 5.2.16 on 2026-08-01 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10014_alter_scheduledemail_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "permissions": [("view_all_clients", "Πρόσβαση σε όλους τους πελάτες ανεξαρτήτως ανάθεσης")],
                "verbose_name": "Προφίλ Πελάτη",
                "verbose_name_plural": "Προφίλ Πελατών",
            },
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_clients", to=settings.AUTH_USER_MODEL, verbose_name="Ανατεθειμένοι Χρήστες"
            ),
        ),
        migrations.CreateModel(
            name="ClientCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("TAXISNET", "Taxisnet"),
                            ("EFKA", "ΕΦΚΑ / ΙΚΑ Εργοδότη"),
                            ("GEMI", "Γ.Ε.ΜΗ."),
                            ("OTHER", "Άλλο"),
                        ],
                        max_length=20,
                        verbose_name="Υπηρεσία",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Περιγραφή για υπηρεσίες τύπου «Άλλο» ή πολλαπλούς λογαριασμούς",
                        max_length=100,
                        verbose_name="Ετικέτα",
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=100, verbose_name="Όνομα Χρήστη")),
                (
                    "_secret_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fernet-encrypted — μην επεξεργάζεστε απευθείας",
                        verbose_name="Κρυπτογραφημένος Κωδικός",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Δημιουργήθηκε")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ενημερώθηκε")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="accounting.clientprofile",
                        verbose_name="Πελάτης",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Τελευταία αλλαγή από",
                    ),
                ),
            ],
            options={
                "verbose_name": "Κωδικός Πελάτη",
                "verbose_name_plural": "Κωδικοί Πελατών",
                "permissions": [("view_client_credential_secret", "Αποκάλυψη κωδικών πελατών")],
                "unique_together": {("client", "service", "label")},
            },
        ),
    ]
