# Generated by Django 5.0.14 on 2026-07-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10012_clientdocument_fts_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Τίτλος")),
                ("notes", models.TextField(blank=True, verbose_name="Σημειώσεις")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Ανοιχτό"), ("completed", "Ολοκληρώθηκε"), ("cancelled", "Ακυρώθηκε")],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="Κατάσταση",
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True, verbose_name="Προθεσμία")),
                ("last_reminder_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Τελευταία Υπενθύμιση")),
                ("reminder_count", models.PositiveSmallIntegerField(default=0, verbose_name="Υπενθυμίσεις")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Ολοκληρώθηκε")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Δημιουργήθηκε")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requests",
                        to="accounting.clientprofile",
                        verbose_name="Πελάτης",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_requests_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Δημιουργήθηκε από",
                    ),
                ),
                (
                    "shared_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_requests",
                        to="accounting.sharedlink",
                        verbose_name="Σύνδεσμος Portal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Αίτημα Εγγράφων",
                "verbose_name_plural": "Αιτήματα Εγγράφων",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRequestItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=200, verbose_name="Περιγραφή")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("registration", "Ιδρυτικά Έγγραφα"),
                            ("contracts", "Συμβάσεις"),
                            ("licenses", "Άδειες & Πιστοποιητικά"),
                            ("correspondence", "Αλληλογραφία"),
                            ("vat", "ΦΠΑ"),
                            ("apd", "ΑΠΔ/ΕΦΚΑ"),
                            ("myf", "ΜΥΦ"),
                            ("payroll", "Μισθοδοσία"),
                            ("invoices_issued", "Εκδοθέντα Τιμολόγια"),
                            ("invoices_received", "Ληφθέντα Τιμολόγια"),
                            ("bank", "Τραπεζικά"),
                            ("receipts", "Αποδείξεις"),
                            ("e1", "Ε1 - Φόρος Εισοδήματος"),
                            ("e2", "Ε2 - Ακίνητα"),
                            ("e3", "Ε3 - Οικονομικά Στοιχεία"),
                            ("enfia", "ΕΝΦΙΑ"),
                            ("balance", "Ισολογισμός"),
                            ("audit", "Έλεγχοι"),
                            ("invoices", "Τιμολόγια"),
                            ("tax", "Φορολογικά"),
                            ("efka", "ΕΦΚΑ"),
                            ("general", "Γενικά"),
                        ],
                        max_length=20,
                        verbose_name="Κατηγορία",
                    ),
                ),
                ("is_received", models.BooleanField(default=False, verbose_name="Ελήφθη")),
                ("received_at", models.DateTimeField(blank=True, null=True, verbose_name="Ελήφθη στις")),
                (
                    "received_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_items",
                        to="accounting.clientdocument",
                        verbose_name="Παραληφθέν Έγγραφο",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accounting.documentrequest",
                        verbose_name="Αίτημα",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ζητούμενο Έγγραφο",
                "verbose_name_plural": "Ζητούμενα Έγγραφα",
                "ordering": ["id"],
            },
        ),
    ]
