# Generated by Django 5.0.14 on 2026-07-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10009_clientdocument_afm_mismatch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyobligation",
            name="attachments",
        ),
    ]
