# Generated by Django 5.0.14 on 2026-07-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10010_remove_monthlyobligation_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedlink",
            name="allow_upload",
            field=models.BooleanField(
                default=False,
                help_text="Ο πελάτης μπορεί να ανεβάζει έγγραφα μέσω του συνδέσμου",
                verbose_name="Επιτρέπεται Upload",
            ),
        ),
        migrations.AddField(
            model_name="sharedlink",
            name="max_uploads",
            field=models.PositiveIntegerField(
                blank=True, help_text="Αν είναι κενό, απεριόριστα", null=True, verbose_name="Μέγιστα Uploads"
            ),
        ),
        migrations.AddField(
            model_name="sharedlink",
            name="upload_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Προεπιλεγμένη κατηγορία για τα αρχεία του πελάτη (κενό = Γενικά)",
                max_length=20,
                verbose_name="Κατηγορία Uploads",
            ),
        ),
        migrations.AddField(
            model_name="sharedlink",
            name="upload_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Πλήθος Uploads"),
        ),
        migrations.AddField(
            model_name="sharedlink",
            name="upload_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Π.χ. λίστα εγγράφων που ζητάμε — εμφανίζεται στο portal",
                verbose_name="Οδηγίες προς Πελάτη",
            ),
        ),
        migrations.AlterField(
            model_name="sharedlinkaccess",
            name="action",
            field=models.CharField(
                choices=[("view", "Προβολή"), ("download", "Λήψη"), ("upload", "Μεταφόρτωση")],
                default="view",
                max_length=20,
                verbose_name="Ενέργεια",
            ),
        ),
    ]
