# Generated by Django 5.2.16 on 2026-08-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10017_remove_plaintext_credential_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "permissions": [
                    ("view_all_clients", "Πρόσβαση σε όλους τους πελάτες ανεξαρτήτως ανάθεσης"),
                    ("send_client_email", "Αποστολή email σε πελάτες"),
                ],
                "verbose_name": "Προφίλ Πελάτη",
                "verbose_name_plural": "Προφίλ Πελατών",
            },
        ),
    ]
