# Generated by Django 5.2.16 on 2026-08-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10023_repair_legacy_slot_chains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voipcalllog",
            name="call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="accounting.voipcall",
                verbose_name="Κλήση",
            ),
        ),
    ]
