# Generated by Django 5.2.16 on 2026-08-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10024_voipcalllog_preserve_on_call_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="voipcalllog",
            name="call_reference",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Αναφορά Κλήσης (snapshot)"),
        ),
        migrations.AddField(
            model_name="voipcalllog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voip_call_logs",
                to="accounting.clientprofile",
                verbose_name="Πελάτης (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="voipcalllog",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Τηλέφωνο (snapshot)"),
        ),
    ]
